modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/Slexom/earth2java/issues"

[[mods]]
modId="earthtojavamobs"
version="2.0.2"
displayName="Earth2Java"
credits="Slexom"
authors="Slexom"
logoFile="logo.png"
displayURL="https://www.curseforge.com/minecraft/mc-mods/earth2java-mobs"
description='''Bring mobs from Minecraft Earth to Minecraft Java Edition.'''
updateJSONURL="https://raw.githubusercontent.com/Slexom/earth2java/master/update.json"

[[dependencies.earthtojavamobs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"



